---
driver:
  name: rackspace
  rackspace_username: <%= ENV['RACKSPACE_USERNAME'] %>
  rackspace_api_key: <%= ENV['RACKSPACE_API_KEY'] %>
  rackspace_region: lon
  require_chef_omnibus: latest
  wait_for: 1200

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: odi-nginx
    run_list: "recipe[odi-nginx]"
    attributes:
    data_bags_path: test/data_bags
